### ISSUE TITLE
Misunderstanding of score

### ISSUE THREAD

**Issue by JordanEckert** [fatihsaglam/rcccd#1]
In using predict() function with RW-CCCD values for e that are not 0 or 1 end up with the error. Fixing if statement to 

 if(!(e >= 0 & e <= 1)) {
    stop("method must be between 0 and 1")
  }

fixes this error

**Comment by fatihsaglam** [comment]
Thank you. I will fix it as soon as possible.

**Comment by fatihsaglam** [comment]
I checked and I did not get any error. Here is an example:

x <- imbalance::banana[,1:2]
y <- imbalance::banana[,3]

library(rcccd)

m <- rwcccd_classifier(x = x, y = y)
predict(object = m, newdata = x, e = 0)
predict(object = m, newdata = x, e = 1)

Both works. I corrected error message but couldn't find any error. Can you
sand me an example?



Fatih Sağlam ***@***.***>, 24 Oca 2024 Çar, 08:51 tarihinde şunu
yazdı:
